"""Initial migration.

Revision ID: 9e45af5934c4
Revises: 
Create Date: 2020-05-22 23:15:14.371803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e45af5934c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_for_service',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posting_categories',
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('categori_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categori_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.id'], ),
    sa.PrimaryKeyConstraint('posting_id', 'categori_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting_categories')
    op.drop_table('user')
    op.drop_table('request_for_service')
    op.drop_table('posting')
    op.drop_table('category')
    op.drop_table('business')
    # ### end Alembic commands ###
